export const BOX_KEYS = {
  INCOME: 'INCOME',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  VARIABLE: 'VARIABLE',
  SAVINGS: 'SAVINGS',
  TITHES: 'TITHES',
  MANUAL_EXPENSES: 'MANUAL_EXPENSES',
};

export const BOX_TITLES_HE = {
  [BOX_KEYS.INCOME]: 'הכנסות',
  [BOX_KEYS.SUBSCRIPTIONS]: 'חשבונות ומנויים',
  [BOX_KEYS.VARIABLE]: 'הוצאות משתנות',
  [BOX_KEYS.SAVINGS]: 'חסכונות',
  [BOX_KEYS.TITHES]: 'מעשרות',
  [BOX_KEYS.MANUAL_EXPENSES]: 'הוצאות ידניות',
};

export const BOX_ORDER = [
  BOX_KEYS.INCOME,
  BOX_KEYS.SUBSCRIPTIONS,
  BOX_KEYS.VARIABLE,
  BOX_KEYS.SAVINGS,
  BOX_KEYS.TITHES,
  BOX_KEYS.MANUAL_EXPENSES,
];

export const EXPENSE_BOXES = [
  BOX_KEYS.SUBSCRIPTIONS,
  BOX_KEYS.VARIABLE,
  BOX_KEYS.SAVINGS,
  BOX_KEYS.TITHES,
  BOX_KEYS.MANUAL_EXPENSES,
];
